# Action Verbs Configuration for Resume Scoring
# Organized by impact level for weighted scoring

# High Impact Verbs (Weight: 3.0) - Leadership, Innovation, Ownership
impact_verbs:
  - "spearheaded"
  - "led"
  - "directed"
  - "managed"
  - "pioneered"
  - "revolutionized"
  - "transformed"
  - "launched"
  - "founded"
  - "established"
  - "initiated"
  - "orchestrated"
  - "championed"
  - "drove"
  - "delivered"
  - "achieved"
  - "accomplished"
  - "executed"
  - "strategized"
  - "optimized"
  - "scaled"
  - "accelerated"
  - "evangelized"
  - "negotiated"
  - "mentored"
  - "coached"
  - "influenced"
  - "empowered"
  - "consolidated"
  - "restructured"
  - "standardized"
  - "strengthened"
  - "elevated"
  - "governed"
  - "incubated"
  - "secured"
  - "maximized"
  - "minimized"
  - "boosted"
  - "increased"
  - "reduced"
  - "improved"
  - "exceeded"
  - "surpassed"
  - "outperformed"
  - "expanded"
  - "globalized"

# Medium Impact Verbs (Weight: 2.0) - Building, Creating, Implementation  
build_verbs:
  - "developed"
  - "built"
  - "created"
  - "implemented"
  - "engineered"
  - "designed"
  - "architected"
  - "programmed"
  - "coded"
  - "constructed"
  - "produced"
  - "generated"
  - "established"
  - "formulated"
  - "configured"
  - "automated"
  - "integrated"
  - "deployed"
  - "migrated"
  - "streamlined"
  - "refactored"
  - "modularized"
  - "containerized"
  - "scripted"
  - "instrumented"
  - "parameterized"
  - "provisioned"
  - "hardened"
  - "prototyped"
  - "synthesized"
  - "indexed"
  - "parallelized"
  - "tuned"
  - "profiled"
  - "compiled"
  - "packaged"
  - "bundled"
  - "minified"
  - "compressed"
  - "encrypted"
  - "decrypted"
  - "parsed"
  - "serialized"
  - "normalized"
  - "standardized"
  - "optimized"
  - "enhanced"
  - "upgraded"
  - "modernized"

# Support Verbs (Weight: 1.0) - Assistance, Collaboration, Maintenance
support_verbs:
  - "assisted"
  - "helped"
  - "supported"
  - "contributed"
  - "collaborated"
  - "participated"
  - "worked"
  - "maintained"
  - "updated"
  - "fixed"
  - "resolved"
  - "debugged"
  - "monitored"
  - "documented"
  - "researched"
  - "analyzed"
  - "tested"
  - "verified"
  - "coordinated"
  - "facilitated"
  - "troubleshot"
  - "audited"
  - "validated"
  - "liaised"
  - "shadowed"
  - "reviewed"
  - "patched"
  - "scheduled"
  - "tracked"
  - "logged"
  - "identified"
  - "observed"
  - "inspected"
  - "checked"
  - "ensured"
  - "followed"
  - "adhered"
  - "complied"
  - "aligned"
  - "synchronized"