# Skills Configuration for Resume Analyzer
# Organized by categories with synonyms support

programming_languages:
  - name: "Python"
    synonyms: ["py", "python3", "python2", "cpython", "python programming"]
  - name: "Java"
    synonyms: ["jvm", "openjdk", "oracle java", "java8", "java11", "java17", "java21", "jdk"]
  - name: "JavaScript"
    synonyms: ["js", "ecmascript", "es6", "es2015", "nodejs", "node.js", "javascript programming", "es2020", "es2021"]
  - name: "C++"
    synonyms: ["cpp", "c plus plus", "cplusplus", "c++11", "c++14", "c++17", "c++20", "cxx"]
  - name: "C#"
    synonyms: ["csharp", "c sharp", "dotnet", "net framework", "microsoft c#"]
  - name: "Go"
    synonyms: ["golang", "go lang", "google go", "go programming"]
  - name: "Rust"
    synonyms: ["rustlang", "rust-lang", "mozilla rust", "rust programming"]
  - name: "PHP"
    synonyms: ["php7", "php8", "hypertext preprocessor", "php programming"]
  - name: "SQL"
    synonyms: ["structured query language", "mysql", "postgresql", "sqlite", "sql server", "t-sql"]
  - name: "HTML"
    synonyms: ["html5", "hypertext markup language", "markup language"]
  - name: "CSS"
    synonyms: ["css3", "cascading style sheets", "stylesheet", "styling"]
  - name: "R"
    synonyms: ["r-lang", "r programming", "rstats"]
  - name: "Ruby"
    synonyms: ["jruby", "mri", "ruby programming"]
  - name: "Swift"
    synonyms: ["swiftlang", "swift programming"]
  - name: "Kotlin"
    synonyms: ["kotlin jvm", "kotlin android", "kotlin programming", "jetbrains kotlin", "kotlin native"]

web_frameworks:
  - name: "React"
    synonyms: ["reactjs", "react.js", "react library", "facebook react", "react frontend"]
  - name: "Angular"
    synonyms: ["angularjs", "angular.js", "angular framework", "google angular", "angular cli"]
  - name: "Vue"
    synonyms: ["vuejs", "vue.js", "vue framework", "vue cli", "progressive vue"]
  - name: "Flask"
    synonyms: ["python flask", "flask framework", "flask web", "flask microframework", "flask api"]
  - name: "Django"
    synonyms: ["django framework", "django web", "django orm", "django rest framework", "drf"]

data_science_libraries:
  - name: "Pandas"
    synonyms: ["pd", "pandas library", "pandas dataframe", "pandas python", "data manipulation"]
  - name: "NumPy"
    synonyms: ["numpy", "np"]
  - name: "Scikit-learn"
    synonyms: ["sklearn", "scikit learn", "sci-kit learn"]
  - name: "TensorFlow"
    synonyms: ["tf", "tensor flow", "tensorflow framework", "google tensorflow", "tensorflow ml"]
  - name: "PyTorch"
    synonyms: ["torch", "pytorch", "pytorch framework", "facebook pytorch", "pytorch neural"]
  - name: "Keras"
    synonyms: ["keras api", "keras neural", "keras tensorflow", "deep learning keras", "keras models"]
  - name: "Matplotlib"
    synonyms: ["pyplot", "plt"]
  - name: "Seaborn"
    synonyms: ["sns", "seaborn plotting", "statistical plots", "seaborn visualization", "python seaborn"]
  - name: "BeautifulSoup"
    synonyms: ["beautiful soup", "bs4"]

cloud_platforms:
  - name: "AWS"
    synonyms: ["amazon web services", "amazon aws", "aws"]
  - name: "Azure"
    synonyms: ["microsoft azure", "azure cloud", "azure"]
  - name: "Google Cloud"
    synonyms: ["gcp", "google cloud platform", "google cloud services", "google cloud"]

devops_tools:
  - name: "Docker"
    synonyms: ["containerization", "containers", "docker containers", "docker images", "container orchestration", "dockerfile", "docker compose"]
  - name: "Kubernetes"
    synonyms: ["k8s", "kube", "container orchestration", "kubectl", "k8s orchestration"]
  - name: "Git"
    synonyms: ["version control", "github", "gitlab", "bitbucket", "git scm", "source control", "vcs", "git version control", "distributed version control"]

databases:
  - name: "MySQL"
    synonyms: ["my sql", "mysql database", "relational database", "mysql server", "mariadb", "mysql workbench"]
  - name: "PostgreSQL"
    synonyms: ["postgres", "psql", "postgresql db", "postgres database", "pg"]
  - name: "MongoDB"
    synonyms: ["mongo", "mongo db", "nosql", "document database", "atlas", "mongodb atlas", "bson"]
  - name: "SQLite"
    synonyms: ["sqlite3", "sql lite", "embedded database"]
  - name: "Redis"
    synonyms: ["redis cache", "redis labs", "in-memory cache", "key-value store", "redis database"]
  - name: "Oracle Database"
    synonyms: ["oracle", "oracle db", "oracle rdbms", "plsql", "pl/sql"]
  - name: "Microsoft SQL Server"
    synonyms: ["sql server", "mssql", "ms sql", "t-sql", "transact-sql", "azure sql"]

project_management:
  - name: "Jira"
    synonyms: ["atlassian jira", "jira software", "issue tracking", "agile jira", "project management jira"]
  - name: "Agile"
    synonyms: ["agile methodology", "agile development"]
  - name: "Scrum"
    synonyms: ["scrum methodology", "scrum master"]

mobile_development:
  - name: "Swift"
    synonyms: ["swiftlang", "swift programming"]
  - name: "Kotlin"
    synonyms: ["kotlin jvm", "kotlin android", "kotlin programming", "jetbrains kotlin", "kotlin native"]
  - name: "Android"
    synonyms: ["android development", "android sdk"]
  - name: "iOS"
    synonyms: ["ios development", "iphone development"]
  - name: "React Native"
    synonyms: ["reactnative", "react-native"]
  - name: "Flutter"
    synonyms: ["dart", "flutter sdk"]

data_engineering:
  - name: "Apache Spark"
    synonyms: ["spark", "pyspark"]
  - name: "Hadoop"
    synonyms: ["hdfs", "mapreduce"]
  - name: "Apache Airflow"
    synonyms: ["airflow", "workflow orchestration"]
  - name: "Kafka"
    synonyms: ["apache kafka", "event streaming"]
  - name: "Snowflake"
    synonyms: ["snowflake db"]
  - name: "BigQuery"
    synonyms: ["google bigquery", "bq"]
  - name: "Redshift"
    synonyms: ["aws redshift", "amazon redshift"]
  - name: "DBT"
    synonyms: ["data build tool", "dbt core"]
  - name: "Delta Lake"
    synonyms: ["databricks delta"]
  - name: "Apache Flink"
    synonyms: ["flink", "stream processing"]

mlops_ai:
  - name: "MLflow"
    synonyms: ["ml flow", "model tracking", "mlflow tracking", "experiment tracking", "ml lifecycle"]
  - name: "Kubeflow"
    synonyms: ["ml kubernetes", "kubeflow pipelines", "ml ops kubernetes", "google kubeflow", "kubernetes ml"]
  - name: "SageMaker"
    synonyms: ["aws sagemaker", "amazon sagemaker"]
  - name: "Ray"
    synonyms: ["ray distributed", "ray ai", "ray framework", "distributed computing", "ray clusters"]
  - name: "DVC"
    synonyms: ["data version control", "dvc ml", "ml data versioning", "iterative dvc", "dvc tracking"]
  - name: "BentoML"
    synonyms: ["model serving", "bentoml framework", "ml model deployment", "bentoml", "model serving platform"]
  - name: "ONNX"
    synonyms: ["open neural network exchange", "onnx format", "model interchange", "onnx runtime", "cross-platform ml"]
  - name: "TensorRT"
    synonyms: ["nvidia tensorrt", "tensor rt", "inference optimization", "gpu inference", "nvidia ai"]
  - name: "Hugging Face"
    synonyms: ["transformers", "hf", "huggingface"]
  - name: "OpenAI"
    synonyms: ["gpt", "chatgpt", "openai api"]
  - name: "LangChain"
    synonyms: ["langchain framework", "lang chain", "llm framework", "ai agent framework", "langchain python"]

infrastructure_observability:
  - name: "Terraform"
    synonyms: ["hashicorp terraform", "tf", "iac"]
  - name: "Ansible"
    synonyms: ["configuration management", "ansible automation", "red hat ansible", "infrastructure automation", "ansible playbooks"]
  - name: "Helm"
    synonyms: ["kubernetes helm", "k8s helm"]
  - name: "Prometheus"
    synonyms: ["monitoring", "metrics"]
  - name: "Grafana"
    synonyms: ["dashboards", "visualization"]
  - name: "OpenTelemetry"
    synonyms: ["otel", "observability"]
  - name: "ELK Stack"
    synonyms: ["elasticsearch", "logstash", "kibana", "elastic stack"]
  - name: "Loki"
    synonyms: ["grafana loki", "log aggregation", "prometheus logging", "loki logging", "cloud native logging"]
  - name: "Jaeger"
    synonyms: ["distributed tracing", "jaeger tracing", "opentracing", "microservices tracing", "cncf jaeger"]
  - name: "Pulumi"
    synonyms: ["infrastructure as code", "pulumi iac", "cloud engineering", "infrastructure programming", "pulumi sdk"]

security_compliance:
  - name: "OWASP"
    synonyms: ["security testing", "web security"]
  - name: "Penetration Testing"
    synonyms: ["pentesting", "ethical hacking"]
  - name: "Threat Modeling"
    synonyms: ["security analysis", "threat modelling", "risk assessment", "security design", "threat identification"]
  - name: "SOC 2"
    synonyms: ["soc2", "compliance"]
  - name: "ISO 27001"
    synonyms: ["iso27001", "information security"]
  - name: "Zero Trust"
    synonyms: ["zero-trust architecture", "zero trust security", "never trust", "zero trust model", "identity-centric security"]
  - name: "SAST"
    synonyms: ["static analysis", "code scanning"]
  - name: "DAST"
    synonyms: ["dynamic analysis", "runtime scanning"]

testing_quality:
  - name: "Jest"
    synonyms: ["javascript testing", "jest framework", "jest js", "facebook jest", "unit testing jest"]
  - name: "Cypress"
    synonyms: ["e2e testing", "end-to-end", "cypress testing", "cypress io", "frontend testing", "integration testing"]
  - name: "Playwright"
    synonyms: ["browser automation", "playwright testing", "microsoft playwright", "e2e playwright", "cross-browser testing"]
  - name: "Selenium"
    synonyms: ["web automation", "selenium webdriver"]
  - name: "JUnit"
    synonyms: ["java testing", "junit framework", "junit5", "junit testing", "unit testing java"]
  - name: "PyTest"
    synonyms: ["python testing", "pytest framework", "pytest", "python unit testing", "test automation python"]

business_intelligence:
  - name: "Tableau"
    synonyms: ["data visualization", "tableau desktop"]
  - name: "Power BI"
    synonyms: ["powerbi", "microsoft power bi"]
  - name: "Looker"
    synonyms: ["looker studio", "google looker"]
  - name: "Superset"
    synonyms: ["apache superset", "superset dashboard", "data visualization", "apache superset", "business intelligence"]
  - name: "Plotly"
    synonyms: ["dash", "plotly dash"]
  - name: "D3.js"
    synonyms: ["d3", "data driven documents"]

ci_cd:
  - name: "GitHub Actions"
    synonyms: ["github workflows", "gh actions"]
  - name: "GitLab CI"
    synonyms: ["gitlab pipeline", "gitlab ci/cd"]
  - name: "Jenkins"
    synonyms: ["jenkins pipeline", "jenkins ci", "continuous integration", "jenkins automation", "devops jenkins"]
  - name: "CircleCI"
    synonyms: ["circle ci", "circleci pipelines", "continuous integration", "ci/cd circle", "cloud ci"]
  - name: "Azure DevOps"
    synonyms: ["azure pipelines", "tfs"]
  - name: "Feature Flags"
    synonyms: ["feature toggles", "launchdarkly"]

frontend_tooling:
  - name: "TypeScript"
    synonyms: ["ts", "typescript lang"]
  - name: "Webpack"
    synonyms: ["module bundler", "webpack bundler", "javascript bundler", "asset bundler", "webpack config"]
  - name: "Vite"
    synonyms: ["build tool", "vite js"]
  - name: "Tailwind CSS"
    synonyms: ["tailwind", "utility css"]
  - name: "SASS"
    synonyms: ["scss", "syntactically awesome stylesheets"]
  - name: "Next.js"
    synonyms: ["nextjs", "react framework"]
  - name: "Nuxt.js"
    synonyms: ["nuxtjs", "vue framework"]

backend_frameworks:
  - name: "Spring Boot"
    synonyms: ["spring", "java spring"]
  - name: "Express.js"
    synonyms: ["express", "node express"]
  - name: "FastAPI"
    synonyms: ["python fastapi", "fast api", "async api", "python web framework", "fastapi framework"]
  - name: "Laravel"
    synonyms: ["php laravel", "laravel framework", "laravel php", "laravel eloquent", "php framework"]
  - name: "Ruby on Rails"
    synonyms: ["rails", "ror"]
  - name: ".NET"
    synonyms: ["dotnet", "asp.net", "c# framework"]

messaging_queues:
  - name: "RabbitMQ"
    synonyms: ["message broker", "amqp"]
  - name: "Redis"
    synonyms: ["caching", "in-memory database"]
  - name: "Apache Pulsar"
    synonyms: ["pulsar", "messaging"]
  - name: "Amazon SQS"
    synonyms: ["sqs", "simple queue service"]

apis_protocols:
  - name: "GraphQL"
    synonyms: ["graph ql", "query language"]
  - name: "REST API"
    synonyms: ["restful", "rest services", "api design"]
  - name: "gRPC"
    synonyms: ["grpc framework", "rpc"]
  - name: "WebSocket"
    synonyms: ["real-time communication", "websocket protocol", "websockets", "bi-directional communication", "full-duplex communication"]
  - name: "Microservices"
    synonyms: ["micro services", "service architecture"]

operating_systems:
  - name: "Linux"
    synonyms: ["unix", "ubuntu", "centos", "redhat", "debian", "fedora", "rhel", "suse", "arch linux", "linux administration"]
  - name: "Windows"
    synonyms: ["windows server", "microsoft windows", "win10", "win11", "windows administration", "active directory"]
  - name: "macOS"
    synonyms: ["mac os", "apple os", "osx", "darwin", "mac operating system"]
  - name: "Unix"
    synonyms: ["unix systems", "unix administration", "solaris", "aix"]

general_skills:
  - name: "Machine Learning"
    synonyms: ["ml", "artificial intelligence", "ai", "deep learning"]
  - name: "Data Analysis"
    synonyms: ["data analytics", "data science", "statistical analysis"]
  - name: "A/B Testing"
    synonyms: ["ab testing", "experimentation", "split testing"]
  - name: "Edge Computing"
    synonyms: ["edge deployment", "cdn"]
  - name: "WebAssembly"
    synonyms: ["wasm", "web assembly"]
  - name: "Blockchain"
    synonyms: ["cryptocurrency", "smart contracts", "web3"]
  - name: "IoT"
    synonyms: ["internet of things", "embedded systems"]

soft_skills:
  - name: "Leadership"
    synonyms: ["team lead", "management", "mentoring", "coaching", "team leadership", "project leadership", "people management"]
  - name: "Communication"
    synonyms: ["presentation", "documentation", "writing", "public speaking", "technical writing", "stakeholder communication"]
  - name: "Problem Solving"
    synonyms: ["analytical thinking", "troubleshooting", "critical thinking", "debugging", "root cause analysis"]
  - name: "Project Management"
    synonyms: ["project coordination", "planning", "scheduling", "resource management", "delivery management"]
  - name: "Collaboration"
    synonyms: ["teamwork", "cross-functional", "stakeholder engagement", "team collaboration", "partnership"]
  - name: "Adaptability"
    synonyms: ["flexibility", "learning agility", "change management", "continuous learning"]